import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

/**
 * The three things about accounts (#31) that break silently rather than loudly, pinned here because
 * none of them shows up in the browser as an error:
 *
 *  - a popup sign-in under `Cross-Origin-Opener-Policy: same-origin` never reports back at all, so
 *    the flow is a full-page redirect and the header stays as it is;
 *  - a `connect-src` that misses the Supabase origin blocks every call to it, and one widened to a
 *    wildcard would let any Supabase project on earth be called from this page;
 *  - the privacy notice is a promise the project made, and a signed-in Save is the moment it stops
 *    being true unless the wording says so.
 *
 * vercel.json is generated by scripts/build-headers.mjs; these read the committed result, which is
 * what Vercel actually serves.
 */
const vercel = JSON.parse(readFileSync(new URL("../vercel.json", import.meta.url), "utf8")) as {
  headers: { headers: { key: string; value: string }[] }[];
};
const header = (key: string): string => {
  const found = vercel.headers.flatMap((h) => h.headers).find((h) => h.key === key);
  expect(found, `${key} is missing from vercel.json`).toBeDefined();
  return found!.value;
};
const csp = new Map(header("Content-Security-Policy").split(";").map((d) => {
  const [name, ...rest] = d.trim().split(/\s+/);
  return [name!, rest] as const;
}));
const html = readFileSync(new URL("../web/index.html", import.meta.url), "utf8");

describe("the headers the account layer has to survive", () => {
  it("keeps COOP at same-origin, which is only safe because sign-in redirects", () => {
    expect(header("Cross-Origin-Opener-Policy")).toBe("same-origin");
  });

  it("names every connect-src origin exactly, with no wildcard", () => {
    const sources = csp.get("connect-src") ?? [];
    expect(sources, "connect-src is missing").not.toHaveLength(0);
    expect(sources).toContain("'self'");
    for (const src of sources) {
      if (src === "'self'") continue;
      expect(src, "a wildcard here would open the page to every Supabase project").not.toContain("*");
      expect(src).toMatch(/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)$/);
    }
  });

  it("carries the Supabase origin the build is configured for", () => {
    const configured = (process.env["SUPABASE_URL"] ?? "").trim().replace(/\/+$/, "");
    // Unset in CI and on a fresh clone: then the only claim to check is the one above.
    if (!configured) return;
    expect(csp.get("connect-src"), "run `npm run headers` after changing SUPABASE_URL").toContain(configured);
  });
});

describe("what the page promises about storing a list", () => {
  it("still says a list is matched in the browser and stored only on an explicit Save", () => {
    const notice = /<p class="notice">([\s\S]*?)<\/p>/.exec(html)?.[1] ?? "";
    expect(notice).toContain("matched in your browser");
    expect(notice).toMatch(/[Nn]othing is stored unless you sign in and press Save/);
  });
});

describe("what the browser bundle is allowed to know", () => {
  it("never mentions the service_role key or the database password in web/", () => {
    for (const f of ["main.ts", "account.ts", "supabase.ts", "graph.ts", "index.html"]) {
      const src = readFileSync(new URL(`../web/${f}`, import.meta.url), "utf8");
      expect(src, f).not.toMatch(/service_role|SERVICE_ROLE|DB_PASSWORD/);
    }
  });
});
