import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

/**
 * The three things about accounts (#31) that break silently rather than loudly, pinned here because
 * none of them shows up in the browser as an error:
 *
 *  - a popup sign-in under `Cross-Origin-Opener-Policy: same-origin` never reports back at all, so
 *    the flow is a full-page redirect and the header stays as it is;
 *  - a `connect-src` that misses the Supabase origin blocks every call to it, and one widened to a
 *    wildcard would let any Supabase project on earth be called from this page;
 *  - the privacy notice is a promise the project made, and a signed-in Save is the moment it stops
 *    being true unless the wording says so.
 *
 * vercel.json is generated by scripts/build-headers.mjs; these read the committed result, which is
 * what Vercel actually serves.
 */
const vercel = JSON.parse(readFileSync(new URL("../vercel.json", import.meta.url), "utf8")) as {
  headers: { headers: { key: string; value: string }[] }[];
};
const header = (key: string): string => {
  const found = vercel.headers.flatMap((h) => h.headers).find((h) => h.key === key);
  expect(found, `${key} is missing from vercel.json`).toBeDefined();
  return found!.value;
};
const csp = new Map(header("Content-Security-Policy").split(";").map((d) => {
  const [name, ...rest] = d.trim().split(/\s+/);
  return [name!, rest] as const;
}));
const html = readFileSync(new URL("../web/index.html", import.meta.url), "utf8");

describe("the headers the account layer has to survive", () => {
  it("keeps COOP at same-origin, which is only safe because sign-in redirects", () => {
    expect(header("Cross-Origin-Opener-Policy")).toBe("same-origin");
  });

  it("names every connect-src origin exactly, with no wildcard", () => {
    const sources = csp.get("connect-src") ?? [];
    expect(sources, "connect-src is missing").not.toHaveLength(0);
    expect(sources).toContain("'self'");
    for (const src of sources) {
      if (src === "'self'") continue;
      expect(src, "a wildcard here would open the page to every Supabase project").not.toContain("*");
      expect(src).toMatch(/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)$/);
    }
  });

  it("carries the Supabase origin the build is configured for", () => {
    const configured = (process.env["SUPABASE_URL"] ?? "").trim().replace(/\/+$/, "");
    // Unset in CI and on a fresh clone: then the only claim to check is the one above.
    if (!configured) return;
    expect(csp.get("connect-src"), "run `npm run headers` after changing SUPABASE_URL").toContain(configured);
  });
});

describe("what the page promises about storing a list", () => {
  it("still says a list is matched in the browser and stored only on an explicit Save", () => {
    const notice = /<p class="notice">([\s\S]*?)<\/p>/.exec(html)?.[1] ?? "";
    expect(notice).toContain("matched in your browser");
    expect(notice).toMatch(/[Nn]othing about it is stored unless you press Save/);
  });

  it("has exactly one way in: the entrance button, and the page starts with the auth state pending (#39)", () => {
    expect(html).toContain('<body data-auth="pending">');
    expect(html.match(/Sign in with Google/g)?.length).toBe(1);
    expect(html).toContain('id="gate-signin"');
    expect(html).not.toContain('id="acct-signin"');
  });
});

/**
 * Riot's "Legal Jibber Jabber" policy prints this sentence and says not to paraphrase it. Four of
 * five Riftbound fan sites get it wrong. It belongs on every page of the site, not only the home
 * page, which is what the two pages added for Google's OAuth branding form made newly true.
 */
const DISCLAIMER = `RiftCombo was created under Riot Games' "Legal Jibber Jabber" policy using assets owned by Riot Games. Riot Games does not endorse or sponsor this project.`;
const PAGES = ["index.html", "privacy.html", "terms.html"];
const page = (f: string) => readFileSync(new URL(`../web/${f}`, import.meta.url), "utf8");

describe("every page the site serves", () => {
  it("carries Riot's disclaimer verbatim", () => {
    for (const f of PAGES) expect(page(f), f).toContain(DISCLAIMER);
  });

  it("sets no inline style attribute, which the CSP forbids", () => {
    for (const f of PAGES) expect(page(f), f).not.toMatch(/<[^>]+\sstyle=/);
  });

  it("is copied into the build output", () => {
    const build = readFileSync(new URL("../scripts/build-web.mjs", import.meta.url), "utf8");
    for (const f of PAGES) expect(build, `${f} would never reach public/`).toContain(`"${f}"`);
  });

  it("is reachable without its extension, which is what /privacy and /terms are linked as", () => {
    const config = JSON.parse(readFileSync(new URL("../vercel.json", import.meta.url), "utf8")) as { cleanUrls?: boolean };
    expect(config.cleanUrls).toBe(true);
  });
});

describe("the top bar is a view switcher, not three anchors (#43)", () => {
  const home = page("index.html");

  it("has no anchors that scroll to a section at the foot of the page", () => {
    expect(home).not.toContain('href="#how"');
    expect(home).not.toContain('href="#data"');
  });

  it("links the four views by hash route", () => {
    for (const h of ["#/combos", "#/decks", "#/guide", "#/sources"]) expect(home, h).toContain(`href="${h}"`);
  });

  it("carries one container per view, and only Combos ships visible", () => {
    for (const name of ["combos", "decks", "guide", "sources"]) {
      expect(home, name).toContain(`id="view-${name}"`);
    }
    // Combos is the default view, so it is the one that ships visible; the router hides it when the
    // hash says otherwise, and the other three never flash before it runs.
    for (const name of ["decks", "guide", "sources"]) {
      expect(new RegExp(`id="view-${name}" hidden`).test(home), `view-${name} must ship hidden`).toBe(true);
    }
  });
});

describe("the order of the deck panel", () => {
  /**
   * The user picked this order and it is not any other layer's to change: the ban list is what a
   * list brought to a tournament wants first (#23), then the status card, then What to add (#18),
   * then Pairs in this deck (#22). Since #43 the saved lists live in their own view, so the panel is
   * the deck input and the four answers about it, and nothing else.
   */
  it("leaves the four result panels in the order the user chose", () => {
    const home = page("index.html");
    const at = (id: string) => {
      const i = home.indexOf(`id="${id}"`);
      expect(i, `#${id} is missing from the deck panel`).toBeGreaterThan(-1);
      return i;
    };
    expect(at("deck-form")).toBeLessThan(at("bans"));
    expect(at("bans")).toBeLessThan(at("status-card"));
    expect(at("status-card")).toBeLessThan(at("plan"));
    expect(at("plan")).toBeLessThan(at("synergy"));
  });
});

describe("what the browser bundle is allowed to know", () => {
  it("never mentions the service_role key or the database password in web/", () => {
    for (const f of ["main.ts", "account.ts", "decks.ts", "router.ts", "supabase.ts", "graph.ts", "index.html"]) {
      const src = readFileSync(new URL(`../web/${f}`, import.meta.url), "utf8");
      expect(src, f).not.toMatch(/service_role|SERVICE_ROLE|DB_PASSWORD/);
    }
  });
});

describe("the tabs are reachable at every width (#49)", () => {
  const css = readFileSync(new URL("../web/styles.css", import.meta.url), "utf8");

  it("never hides .topnav at any breakpoint", () => {
    // `.topnav { display: none }` under 900px is what left My decks, Guide and Sources unreachable on
    // a phone: they used to be anchors that scrolled to sections of the same page, and #43 turned them
    // into views that only the nav can open.
    for (const rule of css.matchAll(/([^{}]*\.topnav[^{}]*)\{([^}]*)\}/g)) {
      const [, selector = "", body = ""] = rule;
      // The gate hides the whole chrome through [data-auth]; ::-webkit-scrollbar hides the scrollbar
      // of the nav, not the nav. Neither takes the tabs away from a player who is signed in.
      if (/data-auth/.test(selector) || /::/.test(selector)) continue;
      expect(body.replace(/\s/g, ""), selector.trim()).not.toMatch(/display:none/);
    }
  });

  it("gives the nav its own row and a sideways scroll below 900px", () => {
    const mobile = /@media \(max-width: 900px\) \{([\s\S]*?)\n\}/.exec(css)?.[1] ?? "";
    expect(mobile).toMatch(/grid-template-areas:\s*"brand acct" "nav format"/);
    expect(mobile).toMatch(/\.topnav\s*\{[^}]*overflow-x:\s*auto/);
  });
});
